require('core.plugin_config.nvim-tree')
require('core.plugin_config.themes.bamboo')
require('core.plugin_config.treesitter')
require('core.plugin_config.undotree')
require('core.plugin_config.lsp')
require('core.plugin_config.fugitive')
require('core.plugin_config.telescope')
require('core.plugin_config.vim-test')
require('core.plugin_config.neotest')
require('core.plugin_config.ale')
require('core.plugin_config.harpoon')

